version: '3.8'

services:
  clairvoyance-web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - clairvoyance-cache

  clairvoyance-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - envs/.env
    volumes:
      - cache:/app/cache

volumes:
  cache:
    driver: local
